### ISSUE TITLE
Filter/sort products

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/american-ale-house#10]
As a **user** I can **filter the products** so that **so that I can view products by category and price**

## Acceptance Criteria
* When I **select the products filter tab** This happens **I get a choice to view products by category or price**

## Tasks
- [x] Create product filter in products view
- [x] Connect URL configuration to navigation tab
- [x] Add sorting js
- [x] add back to top functionality
