### ISSUE TITLE
Secure checkout

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/american-ale-house#23]
As a **customer** I can **checkout securely** so that **I am notified the purchase has been successful**

## Acceptance Criteria
* When I **checkout** This happens **I am notified that the purchase has been completed**

## Tasks
- [x] Create checkout app
- [x] Create checkout view
- [x] Create html template
- [x] Add success message
- [x] Add Stripe
- [x] Connect URL's
