### ISSUE TITLE
Add product to favourites

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/american-ale-house#24]
As a **logged in user** I can **add or remove a product to my favourites** so that **it is quick and easy to purchase the item again**

## Acceptance Criteria
* When I **click the heart icon** This happens **the product is added to my favourites in the nav bar and can be removed from the favourites by selecting remove**

## Tasks
- [x] Create favourites view
- [x] Create favourites.html
- [x] Add html to product details page
- [x] Create add to favourites view
- [x] Create remove from favourites view
- [x] Connect URL's
