### ISSUE TITLE
View profile

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/american-ale-house#25]
As a **logged in user** I can **view my profile** so that **I can add default address and view orders**

## Acceptance Criteria
* When I **click on the profile tab in the nav bar** This happens **I can view my default address and order history**

## Tasks
- [x] Create Profile app
- [x] Create profile model
- [x] Create profile view
- [x] Create template
- [x] Connect URL's
