### ISSUE TITLE
Discount Coupons

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/american-ale-house#26]
As a **user** I can **receive discount codes** so that **I can get free delivery or money off my order**

## Acceptance Criteria
* When I **Sign up to the offers and news letter** This happens **I will receive discount coupons which will make my purchases cheaper**

## Tasks
- [x] Create Beer_token model
- [x] Create coupon view
- [x] Add to html in checkout
