### ISSUE TITLE
Responsive navigation on every page

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/american-ale-house#27]
As a **user** I can **see the same navigation menu on each page** so that **it is easy to understand and use**

## Acceptance Criteria
* When I **see the menu icons in the nav** This happens **I intuitively know where I will be directed to as it is the same on all pages and responsive for smaller screens**

## Tasks
- [x] Create main navigation bar and mobile navigation bar
- [x] Add Icons to navigation and blank links
- [x] Add to base.html template
