### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/american-ale-house#3]
As a ** user** I can **intuitively navigate the site** so that **I can register/ login and search the site products**

## Acceptance Criteria
* When I **see the navigation bar I know where it is going to take me** This happens **I am navigated the the page of my choice**

## Tasks
- [ ] Create base navigation template
- [ ] Create Html and css
- [ ] Connect page urls
