### ISSUE TITLE
Contact us

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/american-ale-house#30]
As a **user** I can **contact the American Ale House via phone or email** so that **I can make contact on any issues I might have**

## Acceptance Criteria
* When I **Click the contact us email link in the footer** This happens **I am taken to a page to email the American Ale House**

## Tasks
- [x] Create contact us view
- [x] Create contact us template
- [x] Create email form
- [x] Connect URL's
