### ISSUE TITLE
Follow on Social Media

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/american-ale-house#32]
As a **user** I can **follow the business on social media** so that **I can keep up to date with latest news and offers**

## Acceptance Criteria
* When I **Click on the social media links in the footer** This happens **I am taken to the sites social media accounts and can follow**

## Tasks
- [x] Create social Media account FB
- [x] Add Icons to footer
- [x] Add links to social accounts
