### ISSUE TITLE
View all products

### ISSUE THREAD

**Issue by Steven-Dawson18** [Steven-Dawson18/american-ale-house#8]
As a **user** I can **browse through all the products** so that **I can choose which one I want to know which one I may want to purchase**

## Acceptance Criteria
* When I **Click to browse all products** This happens **I see a list of all the products I can purchase**

## Tasks
- [x] Create Products app
- [x] Create product models
- [x] Create product view
- [x] Create product to view in admin panel
- [x] Create product.html template
- [x] Connect URL's
